---
# Homebrew environment for the macOS VPN client installs (formula + cask).
homebrew_env:
  PATH: "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:{{ ansible_facts['env'].PATH }}"

homebrew_cask_env:
  PATH: "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:{{ ansible_facts['env'].PATH }}"
  SUDO_ASKPASS: "/tmp/askpass.sh"
